CREATE PROCEDURE FI_SP_DelBeneficiario
    @IDCLIENTE BIGINT,
    @IDsManter dbo.TipoListaID READONLY
AS
BEGIN
    DELETE FROM BENEFICIARIOS
    WHERE IDCLIENTE = @IDCLIENTE
      AND ID NOT IN (SELECT ID FROM @IDsManter);
END